import { config, fields, singleton } from '@keystatic/core';

/**
 * Keystatic storage configuration
 *
 * En local : kind: 'local' fonctionne parfaitement
 * En production Vercel :
 * - kind: 'local' permet de lire le contenu existant mais pas de l'éditer (filesystem read-only après build)
 * - Pour éditer en production, utiliser kind: 'github' avec GitHub App
 *   Nécessite de configurer les variables d'environnement Vercel :
 *   - KEYSTATIC_GITHUB_CLIENT_ID
 *   - KEYSTATIC_GITHUB_CLIENT_SECRET
 *   - KEYSTATIC_SECRET
 *   - KEYSTATIC_GITHUB_REPOSITORY (format: owner/repo)
 * - Alternativement, éditer localement et déployer via Git
 */
export default config({
  storage: {
    kind: 'github',
    repo: 'nderousseaux/anov',
  },
  singletons: {
    hero: singleton({
      label: 'Hero',
      path: 'content/hero',
      schema: {
        image: fields.image({
          label: 'Image de fond',
          directory: 'public/assets',
          publicPath: '/assets/',
        }),
        subtitle_fr: fields.text({
          label: 'Sous-titre 🇫🇷',
          description: 'Texte affiché sous le titre principal sur la page d\'accueil',
        }),
        subtitle_en: fields.text({
          label: 'Sous-titre 🇬🇧',
          description: 'Texte affiché sous le titre principal sur la page d\'accueil',
        }),
        subtitle_de: fields.text({
          label: 'Sous-titre 🇩🇪',
          description: 'Texte affiché sous le titre principal sur la page d\'accueil',
        }),
      },
    }),
    histoire: singleton({
      label: 'Notre Histoire',
      path: 'content/histoire',
      schema: {
        introTitle_fr: fields.text({ label: 'Section 1 — Titre 🇫🇷' }),
        introTitle_en: fields.text({ label: 'Section 1 — Titre 🇬🇧' }),
        introTitle_de: fields.text({ label: 'Section 1 — Titre 🇩🇪' }),
        introText1_fr: fields.text({ label: 'Section 1 — Paragraphe 1 🇫🇷', multiline: true }),
        introText1_en: fields.text({ label: 'Section 1 — Paragraphe 1 🇬🇧', multiline: true }),
        introText1_de: fields.text({ label: 'Section 1 — Paragraphe 1 🇩🇪', multiline: true }),
        introText2_fr: fields.text({ label: 'Section 1 — Paragraphe 2 🇫🇷', multiline: true }),
        introText2_en: fields.text({ label: 'Section 1 — Paragraphe 2 🇬🇧', multiline: true }),
        introText2_de: fields.text({ label: 'Section 1 — Paragraphe 2 🇩🇪', multiline: true }),
        chefImage: fields.image({ label: 'Section 2 — Image', directory: 'public/assets/histoire', publicPath: '/assets/histoire/' }),
        chefName: fields.text({ label: 'Section 2 — Nom du Chef' }),
        chefText1_fr: fields.text({ label: 'Section 2 — Paragraphe 1 🇫🇷', multiline: true }),
        chefText1_en: fields.text({ label: 'Section 2 — Paragraphe 1 🇬🇧', multiline: true }),
        chefText1_de: fields.text({ label: 'Section 2 — Paragraphe 1 🇩🇪', multiline: true }),
        chefText2_fr: fields.text({ label: 'Section 2 — Paragraphe 2 🇫🇷', multiline: true }),
        chefText2_en: fields.text({ label: 'Section 2 — Paragraphe 2 🇬🇧', multiline: true }),
        chefText2_de: fields.text({ label: 'Section 2 — Paragraphe 2 🇩🇪', multiline: true }),
        visionTitle_fr: fields.text({ label: 'Section 3 — Titre 🇫🇷' }),
        visionTitle_en: fields.text({ label: 'Section 3 — Titre 🇬🇧' }),
        visionTitle_de: fields.text({ label: 'Section 3 — Titre 🇩🇪' }),
        visionText1_fr: fields.text({ label: 'Section 3 — Paragraphe 1 🇫🇷', multiline: true }),
        visionText1_en: fields.text({ label: 'Section 3 — Paragraphe 1 🇬🇧', multiline: true }),
        visionText1_de: fields.text({ label: 'Section 3 — Paragraphe 1 🇩🇪', multiline: true }),
        visionText2_fr: fields.text({ label: 'Section 3 — Paragraphe 2 🇫🇷', multiline: true }),
        visionText2_en: fields.text({ label: 'Section 3 — Paragraphe 2 🇬🇧', multiline: true }),
        visionText2_de: fields.text({ label: 'Section 3 — Paragraphe 2 🇩🇪', multiline: true }),
        visionText3_fr: fields.text({ label: 'Section 3 — Paragraphe 3 🇫🇷', multiline: true }),
        visionText3_en: fields.text({ label: 'Section 3 — Paragraphe 3 🇬🇧', multiline: true }),
        visionText3_de: fields.text({ label: 'Section 3 — Paragraphe 3 🇩🇪', multiline: true }),
        visionImage1: fields.image({ label: 'Section 3 — Image 1', directory: 'public/assets/histoire', publicPath: '/assets/histoire/' }),
        visionImage2: fields.image({ label: 'Section 3 — Image 2', directory: 'public/assets/histoire', publicPath: '/assets/histoire/' }),
        productsImage: fields.image({ label: 'Section 4 — Image', directory: 'public/assets/histoire', publicPath: '/assets/histoire/' }),
        productsTitle_fr: fields.text({ label: 'Section 4 — Titre 🇫🇷' }),
        productsTitle_en: fields.text({ label: 'Section 4 — Titre 🇬🇧' }),
        productsTitle_de: fields.text({ label: 'Section 4 — Titre 🇩🇪' }),
        productsText1_fr: fields.text({ label: 'Section 4 — Paragraphe 1 🇫🇷', multiline: true }),
        productsText1_en: fields.text({ label: 'Section 4 — Paragraphe 1 🇬🇧', multiline: true }),
        productsText1_de: fields.text({ label: 'Section 4 — Paragraphe 1 🇩🇪', multiline: true }),
        productsText2_fr: fields.text({ label: 'Section 4 — Paragraphe 2 🇫🇷', multiline: true }),
        productsText2_en: fields.text({ label: 'Section 4 — Paragraphe 2 🇬🇧', multiline: true }),
        productsText2_de: fields.text({ label: 'Section 4 — Paragraphe 2 🇩🇪', multiline: true }),
        teamImage: fields.image({ label: 'Section 5 — Image', directory: 'public/assets/histoire', publicPath: '/assets/histoire/' }),
        teamTitle_fr: fields.text({ label: 'Section 5 — Titre 🇫🇷' }),
        teamTitle_en: fields.text({ label: 'Section 5 — Titre 🇬🇧' }),
        teamTitle_de: fields.text({ label: 'Section 5 — Titre 🇩🇪' }),
        teamText1_fr: fields.text({ label: 'Section 5 — Paragraphe 1 🇫🇷', multiline: true }),
        teamText1_en: fields.text({ label: 'Section 5 — Paragraphe 1 🇬🇧', multiline: true }),
        teamText1_de: fields.text({ label: 'Section 5 — Paragraphe 1 🇩🇪', multiline: true }),
        teamText2_fr: fields.text({ label: 'Section 5 — Paragraphe 2 🇫🇷', multiline: true }),
        teamText2_en: fields.text({ label: 'Section 5 — Paragraphe 2 🇬🇧', multiline: true }),
        teamText2_de: fields.text({ label: 'Section 5 — Paragraphe 2 🇩🇪', multiline: true }),
        teamText3_fr: fields.text({ label: 'Section 5 — Paragraphe 3 🇫🇷', multiline: true }),
        teamText3_en: fields.text({ label: 'Section 5 — Paragraphe 3 🇬🇧', multiline: true }),
        teamText3_de: fields.text({ label: 'Section 5 — Paragraphe 3 🇩🇪', multiline: true }),
        wineTitle_fr: fields.text({ label: 'Section 6 — Titre 🇫🇷' }),
        wineTitle_en: fields.text({ label: 'Section 6 — Titre 🇬🇧' }),
        wineTitle_de: fields.text({ label: 'Section 6 — Titre 🇩🇪' }),
        wineText1_fr: fields.text({ label: 'Section 6 — Paragraphe 1 🇫🇷', multiline: true }),
        wineText1_en: fields.text({ label: 'Section 6 — Paragraphe 1 🇬🇧', multiline: true }),
        wineText1_de: fields.text({ label: 'Section 6 — Paragraphe 1 🇩🇪', multiline: true }),
        wineText2_fr: fields.text({ label: 'Section 6 — Paragraphe 2 🇫🇷', multiline: true }),
        wineText2_en: fields.text({ label: 'Section 6 — Paragraphe 2 🇬🇧', multiline: true }),
        wineText2_de: fields.text({ label: 'Section 6 — Paragraphe 2 🇩🇪', multiline: true }),
        wineText3_fr: fields.text({ label: 'Section 6 — Paragraphe 3 🇫🇷', multiline: true }),
        wineText3_en: fields.text({ label: 'Section 6 — Paragraphe 3 🇬🇧', multiline: true }),
        wineText3_de: fields.text({ label: 'Section 6 — Paragraphe 3 🇩🇪', multiline: true }),
        wineImage: fields.image({ label: 'Section 6 — Image', directory: 'public/assets/histoire', publicPath: '/assets/histoire/' }),
        gestureImage: fields.image({ label: 'Section 7 — Image', directory: 'public/assets/histoire', publicPath: '/assets/histoire/' }),
        gestureTitle_fr: fields.text({ label: 'Section 7 — Titre 🇫🇷' }),
        gestureTitle_en: fields.text({ label: 'Section 7 — Titre 🇬🇧' }),
        gestureTitle_de: fields.text({ label: 'Section 7 — Titre 🇩🇪' }),
        gestureText_fr: fields.text({ label: 'Section 7 — Paragraphe 🇫🇷', multiline: true }),
        gestureText_en: fields.text({ label: 'Section 7 — Paragraphe 🇬🇧', multiline: true }),
        gestureText_de: fields.text({ label: 'Section 7 — Paragraphe 🇩🇪', multiline: true }),
        engagementTitle_fr: fields.text({ label: 'Section 8 — Titre 🇫🇷' }),
        engagementTitle_en: fields.text({ label: 'Section 8 — Titre 🇬🇧' }),
        engagementTitle_de: fields.text({ label: 'Section 8 — Titre 🇩🇪' }),
        engagementText1_fr: fields.text({ label: 'Section 8 — Paragraphe 1 🇫🇷', multiline: true }),
        engagementText1_en: fields.text({ label: 'Section 8 — Paragraphe 1 🇬🇧', multiline: true }),
        engagementText1_de: fields.text({ label: 'Section 8 — Paragraphe 1 🇩🇪', multiline: true }),
        engagementText2_fr: fields.text({ label: 'Section 8 — Paragraphe 2 🇫🇷', multiline: true }),
        engagementText2_en: fields.text({ label: 'Section 8 — Paragraphe 2 🇬🇧', multiline: true }),
        engagementText2_de: fields.text({ label: 'Section 8 — Paragraphe 2 🇩🇪', multiline: true }),
      },
    }),
    origines: singleton({
      label: 'Nos Origines',
      path: 'content/origines',
      schema: {
        title_fr: fields.text({ label: 'Titre 🇫🇷' }),
        title_en: fields.text({ label: 'Titre 🇬🇧' }),
        title_de: fields.text({ label: 'Titre 🇩🇪' }),
        description_fr: fields.text({ label: 'Description 🇫🇷', multiline: true }),
        description_en: fields.text({ label: 'Description 🇬🇧', multiline: true }),
        description_de: fields.text({ label: 'Description 🇩🇪', multiline: true }),
        subtitle_fr: fields.text({ label: 'Sous-titre 🇫🇷', multiline: true }),
        subtitle_en: fields.text({ label: 'Sous-titre 🇬🇧', multiline: true }),
        subtitle_de: fields.text({ label: 'Sous-titre 🇩🇪', multiline: true }),
        besanconLabel: fields.text({ label: 'Label Besançon', description: 'Nom affiché sur la carte (coordonnées fixes)', defaultValue: 'Besançon' }),
        besanconImage: fields.image({ label: 'Image Besançon (hover)', directory: 'public/assets/origins', publicPath: '/assets/origins/' }),
        besanconTitle_fr: fields.text({ label: 'Titre Besançon (hover) 🇫🇷' }),
        besanconTitle_en: fields.text({ label: 'Titre Besançon (hover) 🇬🇧' }),
        besanconTitle_de: fields.text({ label: 'Titre Besançon (hover) 🇩🇪' }),
        besanconDescription_fr: fields.text({ label: 'Description Besançon (hover) 🇫🇷', multiline: true }),
        besanconDescription_en: fields.text({ label: 'Description Besançon (hover) 🇬🇧', multiline: true }),
        besanconDescription_de: fields.text({ label: 'Description Besançon (hover) 🇩🇪', multiline: true }),
        besanconUrl: fields.text({ label: 'URL Besançon (clic)', description: 'Lien externe optionnel' }),
        points: fields.array(
          fields.object({
            label: fields.text({ label: 'Label du point' }),
            latitude: fields.number({ label: 'Latitude', description: 'Ex: 47.2378 pour Besançon' }),
            longitude: fields.number({ label: 'Longitude', description: 'Ex: 6.0244 pour Besançon' }),
            image: fields.image({ label: 'Image (hover)', directory: 'public/assets/origins', publicPath: '/assets/origins/' }),
            title_fr: fields.text({ label: 'Titre (hover) 🇫🇷' }),
            title_en: fields.text({ label: 'Titre (hover) 🇬🇧' }),
            title_de: fields.text({ label: 'Titre (hover) 🇩🇪' }),
            description_fr: fields.text({ label: 'Description (hover) 🇫🇷', multiline: true }),
            description_en: fields.text({ label: 'Description (hover) 🇬🇧', multiline: true }),
            description_de: fields.text({ label: 'Description (hover) 🇩🇪', multiline: true }),
            url: fields.text({ label: 'URL (clic)', description: 'Lien externe optionnel' }),
          }),
          {
            label: 'Points sur la carte',
            itemLabel: (props) => props.fields.label.value || 'Nouveau point',
          }
        ),
      },
    }),
    galerie: singleton({
      label: 'Galerie',
      path: 'content/galerie',
      schema: {
        photos: fields.array(
          fields.object({
            image: fields.image({
              label: 'Image',
              directory: 'public/assets/gallery',
              publicPath: '/assets/gallery/',
            }),
            caption_fr: fields.text({ label: 'Légende 🇫🇷' }),
            caption_en: fields.text({ label: 'Légende 🇬🇧' }),
            caption_de: fields.text({ label: 'Légende 🇩🇪' }),
          }),
          { label: 'Photos' }
        ),
      },
    }),
    contact: singleton({
      label: 'Contact',
      path: 'content/contact',
      schema: {
        image: fields.image({
          label: 'Image de fond',
          directory: 'public/assets/contact',
          publicPath: '/assets/contact/',
        }),
        title_fr: fields.text({ label: 'Titre 🇫🇷' }),
        title_en: fields.text({ label: 'Titre 🇬🇧' }),
        title_de: fields.text({ label: 'Titre 🇩🇪' }),
        subtitle_fr: fields.text({ label: 'Sous-titre 🇫🇷' }),
        subtitle_en: fields.text({ label: 'Sous-titre 🇬🇧' }),
        subtitle_de: fields.text({ label: 'Sous-titre 🇩🇪' }),
        address: fields.text({ label: 'Adresse', multiline: true }),
        phone: fields.text({ label: 'Téléphone' }),
        email: fields.text({ label: 'Email' }),
        hoursLine1_fr: fields.text({ label: 'Horaires — Ligne 1 🇫🇷' }),
        hoursLine1_en: fields.text({ label: 'Horaires — Ligne 1 🇬🇧' }),
        hoursLine1_de: fields.text({ label: 'Horaires — Ligne 1 🇩🇪' }),
        hoursLine2_fr: fields.text({ label: 'Horaires — Ligne 2 🇫🇷' }),
        hoursLine2_en: fields.text({ label: 'Horaires — Ligne 2 🇬🇧' }),
        hoursLine2_de: fields.text({ label: 'Horaires — Ligne 2 🇩🇪' }),
        mapsUrl: fields.text({ label: 'Lien Google Maps' }),
      },
    }),
    menu: singleton({
      label: 'Menu',
      path: 'content/menu',
      schema: {
        heroImage: fields.text({ label: "Hero — URL de l'image" }),
        heroTitle_fr: fields.text({ label: 'Hero — Titre 🇫🇷' }),
        heroTitle_en: fields.text({ label: 'Hero — Titre 🇬🇧' }),
        heroTitle_de: fields.text({ label: 'Hero — Titre 🇩🇪' }),
        heroSubtitle_fr: fields.text({ label: 'Hero — Sous-titre 🇫🇷' }),
        heroSubtitle_en: fields.text({ label: 'Hero — Sous-titre 🇬🇧' }),
        heroSubtitle_de: fields.text({ label: 'Hero — Sous-titre 🇩🇪' }),
        tabs: fields.array(
          fields.object({
            name_fr: fields.text({ label: 'Nom de l\'onglet 🇫🇷' }),
            name_en: fields.text({ label: 'Nom de l\'onglet 🇬🇧' }),
            name_de: fields.text({ label: 'Nom de l\'onglet 🇩🇪' }),
            outline_fr: fields.text({ label: 'Description de l\'onglet 🇫🇷' }),
            outline_en: fields.text({ label: 'Description de l\'onglet 🇬🇧' }),
            outline_de: fields.text({ label: 'Description de l\'onglet 🇩🇪' }),
            image: fields.text({ label: "URL de l'image (facultatif)" }),
            infoBlockTitle_fr: fields.text({ label: 'Info Block — Titre 🇫🇷' }),
            infoBlockTitle_en: fields.text({ label: 'Info Block — Titre 🇬🇧' }),
            infoBlockTitle_de: fields.text({ label: 'Info Block — Titre 🇩🇪' }),
            infoBlockText_fr: fields.text({ label: 'Info Block — Texte 🇫🇷', multiline: true }),
            infoBlockText_en: fields.text({ label: 'Info Block — Texte 🇬🇧', multiline: true }),
            infoBlockText_de: fields.text({ label: 'Info Block — Texte 🇩🇪', multiline: true }),
            infoBlockOutline_fr: fields.text({ label: 'Info Block — Outline 🇫🇷' }),
            infoBlockOutline_en: fields.text({ label: 'Info Block — Outline 🇬🇧' }),
            infoBlockOutline_de: fields.text({ label: 'Info Block — Outline 🇩🇪' }),
            infoBlockPrice: fields.text({ label: 'Info Block — Prix' }),
            categories: fields.array(
              fields.object({
                title_fr: fields.text({ label: 'Titre de la catégorie 🇫🇷' }),
                title_en: fields.text({ label: 'Titre de la catégorie 🇬🇧' }),
                title_de: fields.text({ label: 'Titre de la catégorie 🇩🇪' }),
                image: fields.text({ label: "Image d'arrière-plan (facultatif)" }),
                dishes: fields.array(
                  fields.object({
                    name: fields.text({ label: 'Nom du plat' }),
                    description: fields.text({ label: 'Description', multiline: true }),
                    price: fields.text({ label: 'Prix' }),
                    outline: fields.text({ label: 'Précision' }),
                    allergens: fields.text({ label: 'Allergènes' }),
                    image: fields.text({ label: 'Image URL (facultatif)' }),
                  }),
                  {
                    label: 'Plats',
                    itemLabel: (props) => props.fields.name.value,
                  }
                ),
              }),
              {
                label: 'Catégories',
                itemLabel: (props) => props.fields.title_fr.value,
              }
            ),
          }),
          {
            label: 'Onglets',
            itemLabel: (props) => props.fields.name_fr.value,
          }
        ),
      },
    }),
    footer: singleton({
      label: 'Footer',
      path: 'content/footer',
      schema: {
        description_fr: fields.text({ label: 'Description 🇫🇷', multiline: true }),
        description_en: fields.text({ label: 'Description 🇬🇧', multiline: true }),
        description_de: fields.text({ label: 'Description 🇩🇪', multiline: true }),
        facebookUrl: fields.text({ label: 'Facebook — URL' }),
        instagramUrl: fields.text({ label: 'Instagram — URL' }),
        youtubeUrl: fields.text({ label: 'YouTube — URL' }),
        reviews: fields.array(
          fields.object({
            name: fields.text({ label: 'Plateforme' }),
            rating: fields.text({ label: 'Note' }),
            reviewCount: fields.text({ label: "Nombre d'avis" }),
          }),
          { label: 'Avis' }
        ),
        paymentMethods: fields.text({
          label: 'Moyens de paiement',
          description: 'Ex : CB · Visa · Mastercard · Espèces',
        }),
      },
    }),
    mentionsLegales: singleton({
      label: 'Mentions légales',
      path: 'content/mentions-legales',
      format: { contentField: 'content' },
      schema: {
        title: fields.text({ label: 'Titre' }),
        content: fields.markdoc({
          label: 'Contenu',
        }),
      },
    }),
    politiqueConfidentialite: singleton({
      label: 'Politique de confidentialité',
      path: 'content/politique-de-confidentialite',
      format: { contentField: 'content' },
      schema: {
        title: fields.text({ label: 'Titre' }),
        content: fields.markdoc({
          label: 'Contenu',
        }),
      },
    }),
    cgv: singleton({
      label: 'Conditions Générales de Vente',
      path: 'content/cgv',
      format: { contentField: 'content' },
      schema: {
        title: fields.text({ label: 'Titre' }),
        content: fields.markdoc({
          label: 'Contenu',
        }),
      },
    }),
    boutique: singleton({
      label: 'Boutique / Chèques Cadeaux',
      path: 'content/boutique',
      schema: {
        image: fields.image({
          label: 'Image de fond',
          directory: 'public/assets/boutique',
          publicPath: '/assets/boutique/',
        }),
        title_fr: fields.text({ label: 'Titre 🇫🇷' }),
        title_en: fields.text({ label: 'Titre 🇬🇧' }),
        title_de: fields.text({ label: 'Titre 🇩🇪' }),
        subtitle_fr: fields.text({ label: 'Sous-titre 🇫🇷' }),
        subtitle_en: fields.text({ label: 'Sous-titre 🇬🇧' }),
        subtitle_de: fields.text({ label: 'Sous-titre 🇩🇪' }),
        giftCardsTitle_fr: fields.text({ label: 'Chèques Cadeaux — Titre 🇫🇷' }),
        giftCardsTitle_en: fields.text({ label: 'Chèques Cadeaux — Titre 🇬🇧' }),
        giftCardsTitle_de: fields.text({ label: 'Chèques Cadeaux — Titre 🇩🇪' }),
        giftCardsSubtitle_fr: fields.text({ label: 'Chèques Cadeaux — Sous-titre 🇫🇷' }),
        giftCardsSubtitle_en: fields.text({ label: 'Chèques Cadeaux — Sous-titre 🇬🇧' }),
        giftCardsSubtitle_de: fields.text({ label: 'Chèques Cadeaux — Sous-titre 🇩🇪' }),
        labelAmount_fr: fields.text({ label: 'Label Montant 🇫🇷' }),
        labelAmount_en: fields.text({ label: 'Label Montant 🇬🇧' }),
        labelAmount_de: fields.text({ label: 'Label Montant 🇩🇪' }),
        placeholderAmount_fr: fields.text({ label: 'Placeholder Montant 🇫🇷' }),
        placeholderAmount_en: fields.text({ label: 'Placeholder Montant 🇬🇧' }),
        placeholderAmount_de: fields.text({ label: 'Placeholder Montant 🇩🇪' }),
        amounts: fields.text({
          label: 'Montants disponibles',
          description: 'Séparez les montants par des virgules (ex: 50€, 100€, 150€, 200€, 250€, 500€)',
          defaultValue: '50€, 100€, 150€, 200€, 250€, 500€',
        }),
        labelRecipient_fr: fields.text({ label: 'Label Destinataire 🇫🇷' }),
        labelRecipient_en: fields.text({ label: 'Label Destinataire 🇬🇧' }),
        labelRecipient_de: fields.text({ label: 'Label Destinataire 🇩🇪' }),
        placeholderRecipient_fr: fields.text({ label: 'Placeholder Destinataire 🇫🇷' }),
        placeholderRecipient_en: fields.text({ label: 'Placeholder Destinataire 🇬🇧' }),
        placeholderRecipient_de: fields.text({ label: 'Placeholder Destinataire 🇩🇪' }),
        labelMessage_fr: fields.text({ label: 'Label Message 🇫🇷' }),
        labelMessage_en: fields.text({ label: 'Label Message 🇬🇧' }),
        labelMessage_de: fields.text({ label: 'Label Message 🇩🇪' }),
        placeholderMessage_fr: fields.text({ label: 'Placeholder Message 🇫🇷' }),
        placeholderMessage_en: fields.text({ label: 'Placeholder Message 🇬🇧' }),
        placeholderMessage_de: fields.text({ label: 'Placeholder Message 🇩🇪' }),
        submitButton_fr: fields.text({ label: 'Bouton Achat 🇫🇷' }),
        submitButton_en: fields.text({ label: 'Bouton Achat 🇬🇧' }),
        submitButton_de: fields.text({ label: 'Bouton Achat 🇩🇪' }),
        paymentInfo_fr: fields.text({ label: 'Info Paiement 🇫🇷' }),
        paymentInfo_en: fields.text({ label: 'Info Paiement 🇬🇧' }),
        paymentInfo_de: fields.text({ label: 'Info Paiement 🇩🇪' }),
        footerSecure_fr: fields.text({ label: 'Footer Sécurisé 🇫🇷' }),
        footerSecure_en: fields.text({ label: 'Footer Sécurisé 🇬🇧' }),
        footerSecure_de: fields.text({ label: 'Footer Sécurisé 🇩🇪' }),
        footerValid_fr: fields.text({ label: 'Footer Validité 🇫🇷' }),
        footerValid_en: fields.text({ label: 'Footer Validité 🇬🇧' }),
        footerValid_de: fields.text({ label: 'Footer Validité 🇩🇪' }),
      },
    }),
    giftCardSuccess: singleton({
      label: 'Chèques Cadeaux — Succès',
      path: 'content/gift-card-success',
      schema: {
        title_fr: fields.text({ label: 'Titre 🇫🇷', defaultValue: 'Merci pour votre achat !' }),
        title_en: fields.text({ label: 'Titre 🇬🇧', defaultValue: 'Thank you for your purchase!' }),
        title_de: fields.text({ label: 'Titre 🇩🇪', defaultValue: 'Vielen Dank für Ihren Einkauf!' }),
        confirmationText_fr: fields.text({ label: 'Texte de confirmation 🇫🇷', defaultValue: 'Votre paiement a été traité avec succès.' }),
        confirmationText_en: fields.text({ label: 'Texte de confirmation 🇬🇧', defaultValue: 'Your payment has been processed successfully.' }),
        confirmationText_de: fields.text({ label: 'Texte de confirmation 🇩🇪', defaultValue: 'Ihre Zahlung wurde erfolgreich verarbeitet.' }),
        emailSentTitle_fr: fields.text({ label: 'Titre email envoyé 🇫🇷', defaultValue: 'Un email contenant le chèque cadeau a été envoyé au destinataire.' }),
        emailSentTitle_en: fields.text({ label: 'Titre email envoyé 🇬🇧', defaultValue: 'An email containing the gift card has been sent to the recipient.' }),
        emailSentTitle_de: fields.text({ label: 'Titre email envoyé 🇩🇪', defaultValue: 'Eine E-Mail mit dem Geschenkgutschein wurde an den Empfänger gesendet.' }),
        emailSentDescription_fr: fields.text({
          label: 'Description email 🇫🇷',
          multiline: true,
          defaultValue: 'Le destinataire recevra un code unique valable 12 mois pour profiter d\'une expérience gastronomique chez ANØV.'
        }),
        emailSentDescription_en: fields.text({
          label: 'Description email 🇬🇧',
          multiline: true,
          defaultValue: 'The recipient will receive a unique code valid for 12 months to enjoy a gastronomic experience at ANØV.'
        }),
        emailSentDescription_de: fields.text({
          label: 'Description email 🇩🇪',
          multiline: true,
          defaultValue: 'Der Empfänger erhält einen einzigartigen Code, der 12 Monate lang gültig ist, um ein gastronomisches Erlebnis bei ANØV zu genießen.'
        }),
        helpTitle_fr: fields.text({ label: 'Titre aide 🇫🇷', defaultValue: 'Besoin d\'aide ?' }),
        helpTitle_en: fields.text({ label: 'Titre aide 🇬🇧', defaultValue: 'Need help?' }),
        helpTitle_de: fields.text({ label: 'Titre aide 🇩🇪', defaultValue: 'Brauchen Sie Hilfe?' }),
        helpText_fr: fields.text({
          label: 'Texte aide 🇫🇷',
          defaultValue: 'Contactez-nous si vous avez des questions concernant votre achat.'
        }),
        helpText_en: fields.text({
          label: 'Texte aide 🇬🇧',
          defaultValue: 'Contact us if you have any questions about your purchase.'
        }),
        helpText_de: fields.text({
          label: 'Texte aide 🇩🇪',
          defaultValue: 'Kontaktieren Sie uns, wenn Sie Fragen zu Ihrem Kauf haben.'
        }),
        buttonHome_fr: fields.text({ label: 'Bouton Accueil 🇫🇷', defaultValue: 'Retour à l\'accueil' }),
        buttonHome_en: fields.text({ label: 'Bouton Accueil 🇬🇧', defaultValue: 'Back to home' }),
        buttonHome_de: fields.text({ label: 'Bouton Accueil 🇩🇪', defaultValue: 'Zurück zur Startseite' }),
        buttonAnother_fr: fields.text({ label: 'Bouton Autre achat 🇫🇷', defaultValue: 'Acheter un autre chèque cadeau' }),
        buttonAnother_en: fields.text({ label: 'Bouton Autre achat 🇬🇧', defaultValue: 'Buy another gift card' }),
        buttonAnother_de: fields.text({ label: 'Bouton Autre achat 🇩🇪', defaultValue: 'Einen weiteren Geschenkgutschein kaufen' }),
      },
    }),
    reservation: singleton({
      label: 'Page Réservation',
      path: 'content/reservation',
      schema: {
        image: fields.image({
          label: 'Image de fond',
          directory: 'public/assets',
          publicPath: '/assets/',
        }),
        title_fr: fields.text({ label: 'Titre 🇫🇷', defaultValue: 'Réservez votre table' }),
        title_en: fields.text({ label: 'Titre 🇬🇧', defaultValue: 'Book your table' }),
        title_de: fields.text({ label: 'Titre 🇩🇪', defaultValue: 'Reservieren Sie Ihren Tisch' }),
        subtitle_fr: fields.text({ label: 'Sous-titre 🇫🇷', defaultValue: 'Du mardi au samedi · Service midi et soir' }),
        subtitle_en: fields.text({ label: 'Sous-titre 🇬🇧', defaultValue: 'Tuesday to Saturday · Lunch and dinner service' }),
        subtitle_de: fields.text({ label: 'Sous-titre 🇩🇪', defaultValue: 'Dienstag bis Samstag · Mittags- und Abendessen' }),
      },
    }),
  },
});
