// This file was generated by Prisma, and assumes you have installed the following:
// npm install --save-dev prisma dotenv
import { config } from "dotenv";

const MODE_ALIASES: Record<string, "development" | "preview" | "production"> = {
  dev: "development",
  development: "development",
  preview: "preview",
  preprod: "preview",
  prod: "production",
  production: "production",
};

function resolveAppMode() {
  const rawMode = (process.env.APP_ENV ?? "development").toLowerCase();
  return MODE_ALIASES[rawMode] ?? "development";
}

function resolveEnvFile() {
  if (process.env.ENV_FILE) {
    return process.env.ENV_FILE;
  }

  const mode = resolveAppMode();
  if (mode === "preview") return ".env.preview.local";
  if (mode === "production") return ".env.production.local";
  return ".env.local";
}

config({ path: resolveEnvFile() });
import { defineConfig } from "prisma/config";

export default defineConfig({
  schema: "prisma/schema.prisma",
  migrations: {
    path: "prisma/migrations",
  },
  datasource: {
    url: process.env["DATABASE_URL"] as string,
  },
});
